version: '3'

services:
  database:
    image: mariadb:10.5.2
    ports:
      - 3307:3306
    volumes:
      - .docker/database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'myproject'
      MYSQL_ROOT_PASSWORD: '12345muh'
